version: "3.8"

services:
  back:
    build: back-end/
    image: back-end
    container_name: back-end
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - docker-network
    volumes:
      - ./back-end/src:/app/src
    depends_on:
      - db
    restart: always

  db:
    image: mysql
    container_name: mysql
    command:
      --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - docker-network
    restart: always

  adminer:           
    image: adminer         
    container_name: adminer
    restart: always           
    ports:              
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_DB_DRIVE=${DB_DRIVER}
      - ADMINER_DEFAULT_DB_HOST=mysql
      - ADMINER_DEFAULT_DB_NAME=${DB_NAME}
    depends_on:
      - db
    networks:
      - docker-network


volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "./db"

networks:
  docker-network:
    driver: bridge
