version: "3.8"

services:
  # back:
  #   build: back-end/
  #   image: back-end
  #   container_name: back-end
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - .env
  #   networks:
  #     - docker-network
  #   volumes:
  #     - ./back-end/src:/app/src
  #   depends_on:
  #     - db
  #   restart: always

  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - docker-network
    restart: always

  adminer:           
    image: adminer         
    container_name: adminer
    restart: always           
    ports:              
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_DB_DRIVE=${DB_DRIVER}
      - ADMINER_DEFAULT_DB_HOST=postgres
      - ADMINER_DEFAULT_DB_NAME=${DB_NAME}
    depends_on:
      - db
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
