version: "3.8"

services:
  back:
    build: back-end/
    image: back-end
    container_name: back-end
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - docker-network
    volumes:
      - ./back-end/src:/app/src
    depends_on:
      - db
    restart: always

  db:
    image: mysql
    container_name: mysql
    command:
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # ports:
    #   - "3306:3306"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - docker-network
    restart: always

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${HOME}/data/db"

networks:
  docker-network:
    driver: bridge
