//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq)] 
# [sea_orm (table_name = "users")] 
pub struct Model { 
    # [sea_orm (primary_key , auto_increment = false)] 
    pub login : String , 
    pub profile_pic : String , 
    #[sea_orm (default_value = 0)]
    pub score : Option < i32 > , 
    #[sea_orm (default_value = {})]
    pub r#try : Vec < String > , 
}

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { }

impl ActiveModelBehavior for ActiveModel { }