//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3



use sea_orm :: entity :: prelude :: * ;
use serde::Serialize;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq, Serialize)] # [sea_orm (table_name = "users")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] pub login : String , pub profile_pic : String , pub score : i32 , pub r#try : Vec < String > , pub win : bool , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { }

impl ActiveModelBehavior for ActiveModel { }